name: Factionals
main: fly.factions.Factionals
version: 1.0.0
api-version: 1.13
softdepend: [Vault]
author: FlyGuy3000
commands:
  f:
    description:
  faction:
    description:
  factions:
    description:
  factionals:
    description:
  f:
    rename:
  faction:
    rename:
  factions:
    rename:
  factionals:
    rename:
  f:
    help:
  faction:
    help:
  factions:
    help:
  factionals:
    help:
  f:
    balance:
      view:
      withdraw:
      deposit:
      logs:
  faction:
    balance:
      view:
      withdraw:
      deposit:
      logs:
  factions:
    balance:
      view:
      withdraw:
      deposit:
      logs:
  factionals:
    balance:
      view:
      withdraw:
      deposit:
      logs:
  f:
    permissions:
      view:
      grant:
      revoke:
  faction:
    permissions:
      view:
      grant:
      revoke:
  factions:
    permissions:
      view:
      grant:
      revoke:
  factionals:
    permissions:
      view:
      grant:
      revoke:
