name: Factionals
main: fly.factions.Factionals
version: 1.0.0
api-version: 1.13
softdepend: [Vault]
author: FlyGuy3000
commands:
  f:
    description:
    rename:
    help:
    balance:
      view:
      withdraw:
      deposit:
      logs:
    permissions:
      view:
      grant:
      revoke:
  faction:
    description:
    rename:
    help:
    balance:
      view:
      withdraw:
      deposit:
      logs:
    permissions:
      view:
      grant:
      revoke:
  factions:
    description:
    rename:
    help:
    balance:
      view:
      withdraw:
      deposit:
      logs:
    permissions:
      view:
      grant:
      revoke:
  factionals:
    description:
    rename:
    help:
    balance:
      view:
      withdraw:
      deposit:
      logs:
    permissions:
      view:
      grant:
      revoke:
  
